### PR TITLE
Added Dutch translation

### PR DESCRIPTION
**Pull request by Vistaus**
:)

### CODE REVIEW

**Comment by Vistaus** [comment]
@mesnevi Hey! That's fine :) Thanks! :)

**Comment by scoute-dich** [comment]
Hi, I'm still there, but indeed busy, with some other projects. Also I'm doing this in my free time. I'm very interested in your improvements and waiting for the pull request.

**Comment by mesnevi** [comment]
Hurray! It's so great you haven't abandoned this very project! Could you please merge translation pull requests for RU and NL locales?

**Comment by scoute-dich** [comment]
So, to be honest, I will not have much time in the next weeks, since work started again and, as said I'm doing all this in my free time. So if anyone wants to be a contributor can tell me. Then he could push commits, without making pull requests, which need my attention.

**Comment by mesnevi** [comment]
I'd like to contribute to this application. It's so amazingly simple and exetremely useful, also doesn't contain ads or any additional crap such as 'please install this and that'. The layout is simple and easy to grasp. This is the first app of this kind which lived on my phone longer than two minutes. I also learned a lot while reading sources. Thank you very much for decent job!

**Pull request merged**
